version: '0.9.4'

branches:
  only:
  - release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

services:
  - mongodb

init:
  - git config --global core.autocrlf false

before_build:
  - appveyor-retry dotnet restore -v Minimal

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
  - dotnet build

test_script:
  - dotnet test

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key: oy2lythnb47h6pbqfngq6qqwrjzxbvqepcyoyxtg4hd7ze
  artifact: /.*\.nupkg/