version: '1.6.2.{build}'

branches:
  only:
  - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

init:
- git config --global core.autocrlf false

before_build:
- appveyor-retry dotnet restore -v Minimal
- choco install opencover.portable
- choco install codecov

environment:
 matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
 sonarCubeToken:
    secure: kQ0ruzPw50qAJfN2Qv36sXyA1SGVJbAHB+Zz26HsRrzAaeuEbTeQkysf3A5G/3Dy

build_script:
- dotnet build
- dotnet test

artifacts:
- path: '**\*.nupkg'

deploy:
- provider: NuGet
  symbol_server: https://ci.appveyor.com/nuget/lauchi-jwih9ne6cq4t/api/v2/package
  api_key: e7jrjjfqck2ajelalqvp5sl6
  artifact: /.*\.symbols\.nupkg/

after_build:
- ps: Get-ChildItem .**\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }